shell:
  program: /usr/local/bin/fish
  args:
    - --login

font:
  size: 12

  normal:
    family: Source Code Pro for Powerline
    style: Regular

  bold:
    family: Source Code Pro for Powerline
    style: Bold

  italic:
    family: Source Code Pro for Powerline
    style: Italic
    
  offset:
    x: 0
    y: 3

# Colors (Dracula)
colors:
  # Default colors
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#ff5555'
    green:   '#50fa7b'
    yellow:  '#f1fa8c'
    blue:    '#caa9fa'
    magenta: '#ff79c6'
    cyan:    '#8be9fd'
    white:   '#bfbfbf'

  # Bright colors
  bright:
    black:   '#575b70'
    red:     '#ff6e67'
    green:   '#5af78e'
    yellow:  '#f4f99d'
    blue:    '#caa9fa'
    magenta: '#ff92d0'
    cyan:    '#9aedfe'
    white:   '#e6e6e6'

window:
  padding:
    x: 4
    y: 2

  startup_mode: Fullscreen

key_bindings:
  # https://github.com/alacritty/alacritty/issues/99
  - { key: Space, mods: Control, chars: "\x00" }
